### ISSUE TITLE
NameError: name 'session' is not defined

### ISSUE THREAD

**Issue by prcutler** [prcutler/mlbpool2#1]
View details in Rollbar: [https://rollbar.com/prcutler/mlbpool2/items/1/](https://rollbar.com/prcutler/mlbpool2/items/1/)

```
Traceback (most recent call last):
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/rollbar/contrib/pyramid/__init__.py", line 65, in rollbar_tween
    response = pyramid_handler(request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 124, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/Users/pcutler/workspace/mlbpool/mlbpool/controllers/picks_controller.py", line 161, in submit_player_picks_post
    get_first_name = session.query(Account.first_name).filter(Account.id == self.logged_in_user_id) \
NameError: name 'session' is not definedTraceback (most recent call last):
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 12, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/view.py", line 756, in invoke_exception_view
    raise HTTPNotFound
HTTPNotFound: The resource could not be found.
```

**Comment by prcutler** [comment]
Fixed:  https://github.com/prcutler/mlbpool2/commit/4ee870717a8761aa579db4a97dd0245ab5ba71ca
