### ISSUE TITLE
ConnectionError: HTTPSConnectionPool(host='api.mysportsfeeds.com', port=443): Max retries exceeded with url: /v1.2/pull/mlb/2018-regular/conference_team_standings.json?teamstats=W (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection 

### ISSUE THREAD

**Issue by prcutler** [prcutler/mlbpool2#114]
View details in Rollbar: [https://rollbar.com/prcutler/mlbpool2/items/60/](https://rollbar.com/prcutler/mlbpool2/items/60/)

```
Traceback (most recent call last):
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/rollbar/contrib/pyramid/__init__.py", line 65, in rollbar_tween
    response = pyramid_handler(request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 124, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/srv/mlbpool2/mlbpool/controllers/admin_controller.py", line 219, in update_weekly_stats_post
    WeeklyStatsService.get_league_standings()
  File "/srv/mlbpool2/mlbpool/services/weekly_msf_data.py", line 233, in get_league_standings
    auth=HTTPBasicAuth(config.msf_username, config.msf_pw))
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='api.mysportsfeeds.com', port=443): Max retries exceeded with url: /v1.2/pull/mlb/2018-regular/conference_team_standings.json?teamstats=W (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb7d1922320>: Failed to establish a new connection: [Errno -2] Name or service not known',))Traceback (most recent call last):
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 12, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/view.py", line 756, in invoke_exception_view
    raise HTTPNotFound
HTTPNotFound: The resource could not be found.
```

**Comment by prcutler** [comment]
This was due to an error with MySportsFeeds since resolved.
