### ISSUE TITLE
AttributeError: module 'mlbpool.data.config' has no attribute 'msf_api'

### ISSUE THREAD

**Issue by prcutler** [prcutler/mlbpool2#160]
View details in Rollbar: [https://rollbar.com/prcutler/mlbpool2/items/63/](https://rollbar.com/prcutler/mlbpool2/items/63/)

```
Traceback (most recent call last):
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/rollbar/contrib/pyramid/__init__.py", line 65, in rollbar_tween
    response = pyramid_handler(request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 124, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/srv/mlbpool2/mlbpool/controllers/admin_controller.py", line 227, in update_weekly_stats_post
    WeeklyStatsService.get_hitter_stats()
  File "/srv/mlbpool2/mlbpool/services/weekly_msf_data.py", line 46, in get_hitter_stats
    auth=HTTPBasicAuth(config.msf_api, config.msf_v2pw))
AttributeError: module 'mlbpool.data.config' has no attribute 'msf_api'Traceback (most recent call last):
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 12, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/view.py", line 756, in invoke_exception_view
    raise HTTPNotFound
HTTPNotFound: The resource could not be found.
```

**Comment by prcutler** [comment]
Updated to MSF 2.0 API and forgot to update config.py.  Fixed
