### ISSUE TITLE
OperationalError: (pymysql.err.OperationalError) (1040, 'Too many connections') (Background on this error at: http://sqlalche.me/e/e3q8)

### ISSUE THREAD

**Issue by prcutler** [prcutler/mlbpool2#2]
View details in Rollbar: [https://rollbar.com/prcutler/mlbpool2/items/2/](https://rollbar.com/prcutler/mlbpool2/items/2/)

```
Traceback (most recent call last):
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/rollbar/contrib/pyramid/__init__.py", line 65, in rollbar_tween
    response = pyramid_handler(request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 124, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/Users/pcutler/workspace/mlbpool/mlbpool/controllers/picks_controller.py", line 163, in submit_player_picks_post
    get_first_name = session.query(Account.first_name).filter(Account.id == self.logged_in_user_id) \
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2778, in first
    ret = list(self[0:1])
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2570, in __getitem__
    return list(res)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2878, in __iter__
    return self._execute_and_instances(context)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2899, in _execute_and_instances
    close_with_result=True)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2908, in _get_bind_args
    **kw
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2890, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1029, in connection
    execution_options=execution_options)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1034, in _connection_for_bind
    engine, execution_options)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 403, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 782, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1277, in _do_get
    return self._create_connection()
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 667, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 410, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 935, in connect
    self._get_server_information()
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/

**Comment by prcutler** [comment]
Fixed in commit https://github.com/prcutler/mlbpool2/commit/111b801433d53c3458801a831ea85b7d65b4e885 (I hope)
