### ISSUE TITLE
KeyError: 'activeplayers'

### ISSUE THREAD

**Issue by prcutler** [prcutler/mlbpool2#3]
View details in Rollbar: [https://rollbar.com/prcutler/mlbpool2/items/3/](https://rollbar.com/prcutler/mlbpool2/items/3/)

```
Traceback (most recent call last):
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/rollbar/contrib/pyramid/__init__.py", line 65, in rollbar_tween
    response = pyramid_handler(request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 124, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/Users/pcutler/workspace/mlbpool/mlbpool/controllers/admin_controller.py", line 154, in update_mlb_players_post
    vm.team_id, vm.position, vm.season)
  File "/Users/pcutler/workspace/mlbpool/mlbpool/services/activeplayers_service.py", line 27, in add_active_mlbplayers
    player_list = player_info["activeplayers"]["playerentry"]
KeyError: 'activeplayers'Traceback (most recent call last):
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 12, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/Users/pcutler/workspace/mlbpool/nflpoolvenv/lib/python3.6/site-packages/pyramid/view.py", line 756, in invoke_exception_view
    raise HTTPNotFound
HTTPNotFound: The resource could not be found.
```

**Comment by prcutler** [comment]
Fixed:  https://github.com/prcutler/mlbpool2/commit/6b9a87202a194e553ba485d54f6fb4888a6c1588
