### ISSUE TITLE
InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'p.pick_id' in 'where clause'") [SQL: 'SELECT SUM(w.points_earned) as total_points, a.first_name, a.last_name, a.id from WeeklyPlayerResults w, PlayerPicks p, Account a WHERE w.pick_id = p.

### ISSUE THREAD

**Issue by prcutler** [prcutler/mlbpool2#4]
View details in Rollbar: [https://rollbar.com/prcutler/mlbpool2/items/4/](https://rollbar.com/prcutler/mlbpool2/items/4/)

```
Traceback (most recent call last):
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/rollbar/contrib/pyramid/__init__.py", line 65, in rollbar_tween
    response = pyramid_handler(request)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 124, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/Users/prcutler/workspace/mlbpool2/mlbpool/controllers/standings_controller.py", line 29, in season
    current_standings = StandingsService.display_weekly_standings()
  File "/Users/prcutler/workspace/mlbpool2/mlbpool/services/standings_service.py", line 84, in display_weekly_standings
    standings = session.execute(sqlstr)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1170, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'p.pick_id' in 'where clause'") [SQL: 'SELECT SUM(w.points_earned) as total_points, a.first_name, a.last_name, a.id from WeeklyPlayerResults w, PlayerPicks p, Account a WHERE w.pick_id = p.pick_id AND p.user_id = a.id AND w.season = 2017 AND w.week = (SELECT MAX(week) from WeeklyPlayerResults WHERE season = 2017) GROUP BY p.user_id ORDER BY total_points DESC'] (Background on this error at: http://sqlalche.me/e/2j85)Traceback (most recent call last):
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/Users/prcutler/workspace/mlbpool2/.mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuf

**Comment by prcutler** [comment]
Not a bug - was just testing that rollbar was working
