### ISSUE TITLE
OperationalError: sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'pcweb'@'localhost' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)

 - Expression: "view.logged_in_user_id"


### ISSUE THREAD

**Issue by prcutler** [prcutler/mlbpool2#60]
View details in Rollbar: [https://rollbar.com/prcutler/mlbpool2/items/54/](https://rollbar.com/prcutler/mlbpool2/items/54/)

```
Traceback (most recent call last):
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/rollbar/contrib/pyramid/__init__.py", line 65, in rollbar_tween
    response = pyramid_handler(request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 462, in rendered_view
    request, result, view_inst, context)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/renderers.py", line 435, in render_view
    return self.render_to_response(response, system, request=request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/renderers.py", line 458, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/renderers.py", line 454, in render
    result = renderer(value, system_values)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid_chameleon/zpt.py", line 47, in __call__
    result = self.template(**system)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/chameleon/template.py", line 124, in __call__
    return self.render(**kwargs)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/chameleon/zpt/template.py", line 297, in render
    return super(PageTemplate, self).render(**_kw)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/chameleon/utils.py", line 75, in raise_with_traceback
    raise exc
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "standings_b82dda642a96b66236629ba2a45cb1b3.py", line 316, in render
  File "_layout_4fba8d7f29d39179f4bad4f350ed7981.py", line 916, in render_layout
  File "standings_b82dda642a96b66236629ba2a45cb1b3.py", line 181, in __fill_main_content
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/chameleon/tal.py", line 471, in __call__
    iterable = list(iterable) if iterable is not None else ()
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2889, in __iter__
    return self._execute_and_instances(context)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2910, in _execute_and_instances
    close_with_result=True)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2919, in _get_bind_args
    **kw
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2901, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1035, in connection
    execution_options=execution_options)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1040, in _connection_for_bind
    engine, execution_options)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 784, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1280, in _do_get
    return self._create_connection()
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 667, in __connect
    connection = pool._invoke_creator(self)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 410, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 936, in connect
    self._request_authentication()
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 1156, in _request_authentication
    auth_packet = self._read_packet()
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/err.py", line 107

**Comment by prcutler** [comment]
This sometimes happens when the standings haven't been updated yet.  Not sure why the redirect didn't work.
