### ISSUE TITLE
InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'W2.home_runs' in 'where clause'") [SQL: "INSERT INTO WeeklyPlayerResults (pick_id, season, update_date, points_earned) SELECT t1.pick_id as pick_id, t1.season as season, t1.update_date as 

### ISSUE THREAD

**Issue by prcutler** [prcutler/mlbpool2#63]
View details in Rollbar: [https://rollbar.com/prcutler/mlbpool2/items/57/](https://rollbar.com/prcutler/mlbpool2/items/57/)

```
Traceback (most recent call last):
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/rollbar/contrib/pyramid/__init__.py", line 65, in rollbar_tween
    response = pyramid_handler(request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 124, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/srv/mlbpool2/mlbpool/controllers/admin_controller.py", line 222, in update_weekly_stats_post
    StandingsService.update_player_pick_points()
  File "/srv/mlbpool2/mlbpool/services/standings_service.py", line 138, in update_player_pick_points
    session.execute(sqlstr)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1176, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'W2.home_runs' in 'where clause'") [SQL: "INSERT INTO WeeklyPlayerResults (pick_id, season, update_date, points_earned) SELECT t1.pick_id as pick_id, t1.season as season, t1.update_date as update_date, (pts.points*t1.multiplier*t1.changed) as points_earned FROM (SELECT p.pick_id, p.user_id, p.multiplier, IF(p.changed=1,0.5,1) as changed, p.player_id, (SELECT count(*) from WeeklyMLBPlayerStats as w2, ActiveMLBPlayers as ap, TeamInfo as t WHERE w2.update_date = '2018-04-07' AND w2.season = 2018 AND w2.player_id = ap.player_id AND ap.team_id = t.team_id AND t.league_id = 0 AND W2.home_runs>w.home_runs)+1 as rank, w.update_date, w.season FROM WeeklyMLBPlayerStats w, PlayerPicks p WHERE w.player_id = p.player_id AND  w.season = 2018 AND w.update_date = '2018-04-07' AND p.pick_type = 4 AND p.league_id = 0 AND w.home_runs IS NOT NULL ORDER BY rank) as t1, PickTypePoints pts WHERE pts.pick_type_id = 4 AND t1.rank = pts.rank"] (Background on this error at: http://sqlalche.me/e/2j85)Traceback (most recent call last):
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/srv/mlbpoolvenv/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)

**Comment by prcutler** [comment]
It helps if one of the services isn't commented out when trying to update standings
